# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x19\x61pi_design.bookstore.book\"\xd4\x01\n\x04\x42ook\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x34\n\x05genre\x18\x04 \x01(\x0e\x32%.api_design.bookstore.book.Book.Genre\x12\x17\n\x0fpublishing_year\x18\x05 \x01(\x05\"P\n\x05Genre\x12\x13\n\x0fSCIENCE_FICTION\x10\x00\x12\x0b\n\x07HISTORY\x10\x01\x12\r\n\tBIOGRAPHY\x10\x02\x12\x0b\n\x07\x46\x41NTASY\x10\x03\x12\t\n\x05OTHER\x10\x04\"\xc3\x01\n\rInventoryItem\x12\x14\n\x0cinventory_id\x18\x01 \x01(\t\x12/\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x1f.api_design.bookstore.book.BookH\x00\x12?\n\x06status\x18\x03 \x01(\x0e\x32/.api_design.bookstore.book.InventoryItem.Status\"\"\n\x06Status\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x42\x06\n\x04itemb\x06proto3')



_BOOK = DESCRIPTOR.message_types_by_name['Book']
_INVENTORYITEM = DESCRIPTOR.message_types_by_name['InventoryItem']
_BOOK_GENRE = _BOOK.enum_types_by_name['Genre']
_INVENTORYITEM_STATUS = _INVENTORYITEM.enum_types_by_name['Status']
Book = _reflection.GeneratedProtocolMessageType('Book', (_message.Message,), {
  'DESCRIPTOR' : _BOOK,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:api_design.bookstore.book.Book)
  })
_sym_db.RegisterMessage(Book)

InventoryItem = _reflection.GeneratedProtocolMessageType('InventoryItem', (_message.Message,), {
  'DESCRIPTOR' : _INVENTORYITEM,
  '__module__' : 'book_pb2'
  # @@protoc_insertion_point(class_scope:api_design.bookstore.book.InventoryItem)
  })
_sym_db.RegisterMessage(InventoryItem)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOK._serialized_start=42
  _BOOK._serialized_end=254
  _BOOK_GENRE._serialized_start=174
  _BOOK_GENRE._serialized_end=254
  _INVENTORYITEM._serialized_start=257
  _INVENTORYITEM._serialized_end=452
  _INVENTORYITEM_STATUS._serialized_start=410
  _INVENTORYITEM_STATUS._serialized_end=444
# @@protoc_insertion_point(module_scope)
