# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventoryservice.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import book_pb2 as book__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16inventoryservice.proto\x12%api_design.bookstore.inventoryservice\x1a\nbook.proto\"B\n\x11\x43reateBookRequest\x12-\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x1f.api_design.bookstore.book.Book\"\"\n\x12\x43reateBookResponse\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\"N\n\x0fGetBookResponse\x12\x32\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x1f.api_design.bookstore.book.BookH\x00\x88\x01\x01\x42\x07\n\x05_book2\x90\x02\n\x10InventoryService\x12\x81\x01\n\nCreateBook\x12\x38.api_design.bookstore.inventoryservice.CreateBookRequest\x1a\x39.api_design.bookstore.inventoryservice.CreateBookResponse\x12x\n\x07GetBook\x12\x35.api_design.bookstore.inventoryservice.GetBookRequest\x1a\x36.api_design.bookstore.inventoryservice.GetBookResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventoryservice_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEBOOKREQUEST._serialized_start=77
  _CREATEBOOKREQUEST._serialized_end=143
  _CREATEBOOKRESPONSE._serialized_start=145
  _CREATEBOOKRESPONSE._serialized_end=179
  _GETBOOKREQUEST._serialized_start=181
  _GETBOOKREQUEST._serialized_end=211
  _GETBOOKRESPONSE._serialized_start=213
  _GETBOOKRESPONSE._serialized_end=291
  _INVENTORYSERVICE._serialized_start=294
  _INVENTORYSERVICE._serialized_end=566
# @@protoc_insertion_point(module_scope)
